### ISSUE TITLE
Show named requests in the history of command palate

### ISSUE THREAD

**Issue by amittendulkar** [kylebebak/Requester#12]
This request is very similar to request #11 (thanks for considering it).

If I have named requests in my script that send request to the same URL but with different POST body, they don't show up as different requests in the request history through the command palate.

Can you please make the requests history show the request names as well (so inherently separate out the different named requests to the same URL)?

**Comment by kylebebak** [comment]
This is a good idea as well, and will make the `tabname` argument more useful.

**Comment by kylebebak** [comment]
Added this feature, now `tabname` is included in fuzzy searchable request history.

Check out the **Custom Tab Name** section of the docs. Give it a try, let me know what you think!

**Comment by amittendulkar** [comment]
Thanks. I will try it out.
