### ISSUE TITLE
Incorrect unicode symbols display

### ISSUE THREAD

**Issue by eremin-n-s** [kylebebak/Requester#21]
**OS:** macOS Mojave 10.14.3
**Problem:** unicode symbols in response body (json) display incorrect;

**Example:**

**Request:** `get('https://api.partiyaedi.ru/api/v3/goods/actual')`
**Response (partial):** `        "ingredients": [
            {
              "amount": 4,
              "name": "\u0422\u0438\u043c\u044c\u044f\u043d",
              "units": "\u0433"
            },`

**Comment by kylebebak** [comment]
Thanks for creating the issue. I'll look into this.

**Comment by kylebebak** [comment]
@eremin-n-s 

This is fixed now, thanks for bringing it to my attention! I'll push a new version later today.

**Comment by kylebebak** [comment]
Fix is out in 2.37.2, I'm going to close this.

f275ab4

Give this a try and let me know if something isn't working right!

**Comment by eremin-n-s** [comment]
It's ok now, thanks a lot!
