### ISSUE TITLE
Documentation site down? 

### ISSUE THREAD

**Issue by yijia-zhan** [kylebebak/Requester#28]
Looks like the documentation site is down?

![image](https://user-images.githubusercontent.com/5067289/93787087-e6b5a280-fbe4-11ea-8d31-2df0e695c8a6.png)

**Comment by kylebebak** [comment]
I forgot to renew the domain, and Namecheap auctioned it off and now wants to sell it back to me for $670.00

Docs site moved to https://kylebebak.github.io/Requester/ in `2.39.3`, which I just published.
