### ISSUE TITLE
The whole Sublime Text gets frozen if http-server is killed in the middle of request-execution.

### ISSUE THREAD

**Issue by piddubnyi** [kylebebak/Requester#29]
Steps to reproduce:
 - Start http-server application in debug mode (I'm using java-spring stack)
 - Set breakpoint somewhere in the middle of request-processing
 - Issue request from Requester (debug got triggered)
 - Kill the server without resuming debug

Whole sublime gets frozen and does not react to any actions (including closing).

Sublime 3.2.2
Ubuntu 20.04.1 LTS

**Comment by kylebebak** [comment]
This is something of an edge case, but is also very likely a bug. It sounds like `requests` doesn't raise an exception in this case, and some thread in Sublime blocks forever. A timeout for these scenarios might be necessary

**Comment by piddubnyi** [comment]
Recently found that the issue is actually caused by broken UI.
The Info-window with a timeout message actually **is** shown, but the background, while actual Sublime editor is in the foreground. 

So it looks like sublime is frozen until you alt-tab to the info-window and close it.
However, this has nothing to do with Requester.
