### ISSUE TITLE
Support RAW Http Requests

### ISSUE THREAD

**Issue by TheSecEng** [kylebebak/Requester#35]
**What**

Supporting a raw function to pass RAW HTTP requests into.

```
raw('''
GET /api/endpoint HTTP1.1
Host: trmnl.io
Cookie: xyz:123
''')
```

**Comment by kylebebak** [comment]
This would require writing a new parser. The new parser would be a lot more complex than the existing one, whose syntax is almost identical to the `requests` API. In other words, this would be a huge undertaking and is not in scope for the plugin
