### ISSUE TITLE
Issues with localhost environments

### ISSUE THREAD

**Issue by any626** [kylebebak/Requester#4]
I can't requests localhost environments. I get `Connection Error: check your connection`, but when I hit public sites I have no issue. No issues when using postman.

**Comment by kylebebak** [comment]
@any626 
Alejandro, please include steps to reproduce your problem. At the very least this means your OS, the request you're sending, your env block, and the working request in Postman.

Requester uses **Requests** under the hood, and this library has no issues with hitting localhost. For example, I just tried running booting **httpbin** on my machine on port `8000`.

Both of the following requests work for me:

- `requests.get('http://127.0.0.1:8000/get')`
- `requests.get('http://localhost:8000/get')`

**Comment by any626** [comment]
I installed and completed the Package Control: Satisfy Dependencies steps.

I write `requests.get('https://www.google.com')` and hit ctrl+r and its successful.
I repeat the same steps for`requests.get('http://127.0.0.1')` or hosts file entries on 127.0.0.1 results in the same error. I've checked the nginx access.log and there are records for status 301.
Entry in nginx accesslog only occurs if i do not include https. Manually insert http or defaulting to it results in the entry.

I'm on macOS Sierra 10.12.6 using macports. Not using an env block.

**Comment by kylebebak** [comment]
Can you read a response when hitting this endpoint using either `http` or `https`? Is it still displaying a connection error?

Thanks for OS info. Again, I have no trouble hitting localhost with requests, and I'm on the macOS Sierra 10.12 as well.

Here's a request to `httpbin` running on localhost:
<img width="866" alt="screen shot 2017-09-15 at 11 10 34 am" src="https://user-images.githubusercontent.com/1524088/30492607-b4e503f6-9a06-11e7-911e-f21a91624ae4.png">

And here's a request to `127.0.0.1`. It gives the **same response** as `curl 127.0.01`.
<img width="871" alt="screen shot 2017-09-15 at 11 09 21 am" src="https://user-images.githubusercontent.com/1524088/30492684-f22d8be8-9a06-11e7-8365-e1bf32dd50a8.png">

You told me the response returned by Postman is different, but you still haven't shown me that response. Could you try hitting the same localhost endpoint with `curl` and tell me what you get?

I'm going to close this issue for the time being, if you can provide me with info showing what's wrong I'll be glad to fix it immediately. Thanks

**Comment by any626** [comment]
My mistake, I was a bit unclear. I do not receive or get a response page from sublime text. Just the popup error. On Postman I receive a response. I didn't paste any response from postman as the issue was that I wasn't getting a response from sublime. I get the correct behavior when hitting public pages. If you need more info let me know.

**Comment by kylebebak** [comment]
Could you try sending a request to the localhost endpoint using `curl`, then paste both the request and the response?

**Comment by any626** [comment]
With the latest update, i'm able to get a more detailed error.

`requests.get('https://localhost')
Connection Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)`

I'm using local encrypted certs, is there a way to pass them or not validate the certs?

**Comment by any626** [comment]
I believe in Request you can pass verify false to bypass verification.
http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by kylebebak** [comment]
@any626 
Hey, that's interesting. I'm glad the more detailed debug message helped you find the source of the problem.

Remember, Requester's syntax is a superset of Requests' syntax. Any args that are valid for Requests are also valid for Requester. Try passing `verify=False` to the request you're sending and see if that works.

**Comment by any626** [comment]
Ha got it working! Gave it a try with `verify=false` but forgot python used `False`.  Thank you!

**Comment by kylebebak** [comment]
No problem, I'm glad it's working for you =)
