### ISSUE TITLE
assertion on JSON value

### ISSUE THREAD

**Issue by doodi-v1** [kylebebak/Requester#8]
assert currently works to test a limited set of response header values and a JSON structure:

assert {
  'status_code': 200,
  'json_schema': {
    'success': 'number',
    'message': 'string',
    'location': 'string',
    'serialGUID': 'string',
    'serialNumber': 'string'
  }
}

I would like the ability to also check for JSON field values, something like:

assert {
  'status_code': 200,
  'json_schema': {
    'success': 'number',
    'message': 'string',
    'location': 'string',
    'serialGUID': 'string',
    'serialNumber': 'string'
  },
  **'json_value:{
    'success': 1,
    'message': 'OK'
  }**
}

NEQ would also be nice but EQ would be great - and as in the example unspecified values (location, serialGUID, serialNumber) would not be compared and would not fail the assertion.

**Comment by kylebebak** [comment]
@doodi-v1 

This would be a nice feature to add, but I have to think about the easiest way to implement it. From the docs:

> `cookies`, `headers` and `json` point to Python dicts or lists, which means comparing for equality isn’t very useful. Much more useful are the following special assertion keys for these properties: `cookies_schema`, `headers_schema`, `json_schema`.

Perhaps we could do something very generic, like add an assertion key called `response_test`, which must be a function that accepts the response object and returns a boolean. If the boolean is `True` the test passes, else it fails.

This could handle this use case and other use cases as well, without having to write a likely complex function that could parse the `json_value` key you're proposing and compare it with the JSON content of the response.

**Comment by doodi-v1** [comment]
That would work. My json_value suggestion was just the first thing the popped into my head and was simply using the json_schema theme.

**Comment by kylebebak** [comment]
Hey, just finished adding this feature, thanks for the suggestion =)

It will be released in `2.25.0` in about an hour. Check the "Test Runner" section [of the docs](http://requester.org) to see how it works.

**Comment by doodi-v1** [comment]
Perfect! I can't wait to give it a try.
