### ISSUE TITLE
Export to cURL: include basic authentication

### ISSUE THREAD

**Issue by YayC** [kylebebak/Requester#9]
Exporting `get('https://example.com', auth=('key', ))` to cURL results in:
```
curl -X GET 'https://example.com'
```
Ideally this would be:
```
curl -X GET -u 'key:' 'https://example.com'
```

Using Requester v2.24.1, Sublime v3.1.1 build 3176, mac OS 10.13.5

**Comment by kylebebak** [comment]
Hey there, thanks for the suggestion! Just added this. It will be released in an hour or so in `2.25.0`.
